<?php
/**
 * @file
 * Module to allow users the ability to add notes to articles
 * The getters and setters.
 */

/**
 * Implements hook_help().
 */
function jdt_user_notes_help($path, $arg) {
  if ($path == 'admin/help#jdt_user_notes') {
    return t('This module will enable users to add notes to articles');
  }
}

/**
 * Implements hook_permission().
 */
function jdt_user_notes_permission() {
  return array(
    'add notes' => array(
      'title' => t('allow user to add notes'),
      'description' => t('Allow users to add notes'),
    ),
    'access notes' => array(
      'title' => t('allow user to access notes'),
      'description' => t('Allow users to access notes'),
    ),
    'modify notes' => array(
      'title' => t('allow user to modify their own notes'),
      'description' => t('Allow users to modify their own notes'),
    ),
    'delete notes' => array(
      'title' => t('Allow user to delete notes'),
      'description' => t('Allow users to delete notes'),
    ),
  );
}

/*
 * Implement hook_theme().
 */
function jdt_user_notes_theme(){
  return array(
    'jdt_user_notes_template' => array(
      'template' => 'annotation-page',
    ),
  );
}


/**
 * Implements hook_menu().
 */
function jdt_user_notes_menu() {
  $items['node/%node/note/add'] = array(
    'title' => 'Annotate',
    'description' => 'Add a user note.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jdt_user_notes_gen_form', 1),
    'access arguments' => array('add notes'),
    'weight' => 50,
    'type' => MENU_LOCAL_TASK,
    'file' => 'jdt_user_notes.forms.inc',
  );
  $items['node/%node/note/%/edit'] = array(
    'title' => 'Edit JDT User Notes',
    'description' => 'Edit existing user notes.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jdt_user_notes_gen_edit_form', 3),
    'access arguments' => array('modify notes'),
    'weight' => 50,
    'type' => MENU_CALLBACK,
    'file' => 'jdt_user_notes.forms.inc',
  );
  $items['node/%node/gimme'] = array(
    'title' => 'All related annotations',
    'description' => 'Shows all Annotations for node.',
    'page callback' => 'jdt_user_notes_gimme',
    'page arguments' => array(1),
    'access arguments' => array('access notes'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'jdt_user_notes.helpers.inc',
  );

  return $items;
}






