<?php
/**
 * @file
 * Module to allow users the ablity to add notes to articles
 */

/**
 * Implement hook_help()
 */

function jdt_user_notes($path, $arg) {
  if ($path == 'admin/help#jdt_user_notes') {
    return t('This module will enable users to add notes to articles');
  }
}

/**
 * Implement hook_permission()
 */

function jdt_user_notes_permission() {
    return array(
        'add notes' => array(
            'title' => t('allow user to add notes'),
            'description' => t('Allow users to add notes'),
        ),
        'access notes' => array(
            'title' => t('allow user to access notes'),
            'description' => t('Allow users to access notes'),
        ),
        'modify notes' => array(
            'title' => t('allow user to modify their own notes'),
            'description' => t('Allow users to modify their own notes'),
        ),
        'delete notes' => array(
            'title' => t('Allow user to delete notes'),
            'description' => t('Allow users to delete notes'),
        ),
    );
}



/**
 * Implements hook_menu().
 */

function jdt_user_notes_menu() {
    $items['notes/%/add'] = array(
        'title' => 'JDT User Notes',
        'description' => 'Add a user note.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jdt_user_notes_new_form'),
        //'access arguments' => array('access note form'),
        'access callback' => array('add notes'),
        'weight' => 50,
        'type' => MENU_CALLBACK,
        'file' => 'jdt_user_notes.admin.inc',
    );
    $items['notes/%/edit'] = array(
        'title' => 'Edit JDT User Notes',
        'description' => 'Edit existing user notes.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jdt_user_notes_new_form'),
        'access arguments' => array('access note form'),
        'access callback' => array('add notes'),
        'weight' => 50,
        'file' => 'jdt_user_notes.admin.inc',
    );

    return $items;
}






